### ISSUE TITLE
dijkstra.bidirectional wrong result on weight=0

### ISSUE THREAD

**Issue by yoursunny** [graphology/graphology-shortest-path#11]
```js
const { DirectedGraph } = require('graphology');
const dijkstra = require('graphology-shortest-path/dijkstra');

const graph = new DirectedGraph();
graph.addNode('A');
graph.addNode('B');
graph.addNode('C');

graph.addEdge('A', 'B', { weight: 0 });
graph.addEdge('A', 'C', { weight: 0 });
graph.addEdge('B', 'C', { weight: 1 });

console.log(dijkstra.bidirectional(graph, 'A', 'C'));
```

In this graph, there's two possible paths from A to C:

* A-B-C: cost is 1.
* A-C: cost is 0.

The algorithm selects A-B-C path, which has a higher cost than A-C path.

Environment:

* Node.js 14.x
* graphology ^0.17.1
* graphology-shortest-path ^1.3.3

**Comment by Yomguithereal** [comment]
Thanks @yoursunny. The bug should be fixed in the newly released v1.3.4
