### ISSUE TITLE
[REQUEST] Return path cost using dijkstra

### ISSUE THREAD

**Issue by didix16** [graphology/graphology-shortest-path#12]
Hello guys. Thanks for doing this great library to handle graphs.

I have a request for you. It could be possible that functions like #shortestPath(graph, source, target?) returns the path cost?

If no, then how can I draw the graph and on each edge render the accomulated weight since then ?

Thank you in advance.

**Comment by Yomguithereal** [comment]
Hello @didix16, one workaround without adding a dedicated function could be to get the edge representing the path and accumulate the weights on the way (I'll assume you have a simple directed or undirected graph):

```js
var currentCost = 0;

var accumulatedCosts = path.map(function(target, i) {
  if (i === 0) {
    return currentCost;
  }

  var source = path[i - 1];

  currentCost += graph.getEdgeAttribute(source, target, 'weight');

  return currentCost;
});
```

**Comment by didix16** [comment]
Thanks @Yomguithereal for your answer. I'll try your proposal :)

**Comment by Yomguithereal** [comment]
@didix16 come back and tell me if this fits the issue and I'll let you close it. We could also think to add some such helpers to the library itself possibly if useful.

**Comment by didix16** [comment]
@Yomguithereal yeah it worked. Thanks a lot :). In the future it could be nice that dijkstra also returns the total path weight for example or that you could pass a callback for each edge in the path.

Thank you!
