### ISSUE TITLE
Directed Graph Returning Path without Target 

### ISSUE THREAD

**Issue by pmoelgaard** [graphology/graphology-shortest-path#3]
![2018-04-13_11-45-23](https://user-images.githubusercontent.com/1098964/38717456-390846ac-3f11-11e8-9dc3-68cb11b8e528.png)

**Comment by Yomguithereal** [comment]
Hello @pmoelgaard. Does some other cases return the target in the path? Just to know if it's a consistency issue or an API one?

**Comment by pmoelgaard** [comment]
Yes, other graphs returns with the target.
However, what I have done is to switch to singleSource, and then just filter on the end node to match the target, just an easy workaround with some performance issues, but for now a satisfactory work-around.

**Comment by pmoelgaard** [comment]
Sure, I will dump the graph into a file, any particular format your prefer ?

**Comment by pmoelgaard** [comment]
Found this one, will use that approach...
https://graphology.github.io/serialization.html#format

**Comment by Yomguithereal** [comment]
Any news @pmoelgaard?
