### ISSUE TITLE
dijkstra.bidirectional returns undefined if the edges don't have a weight attribute

### ISSUE THREAD

**Issue by brendanwheble** [graphology/graphology-shortest-path#9]
Maybe it's my misunderstanding, but weight didn't appear to be a mandatory attribute. At least, I'd expect it to default to 1.

To recreate:

Create edges but don't define any attributes. 

The code affected is below

      if (u in distances[dir] && cost < distances[dir][u]) {
        throw Error('graphology-shortest-path/dijkstra: contradictory paths found. Do some of your edges have a negative weight?');
      }
      else if (!(u in seen[dir]) || cost < seen[dir][u]) {
        console.log('>');
        seen[dir][u] = cost;
        fringe[dir].push([cost, count++, u]);
        paths[dir][u] = paths[dir][v].concat(u);

        if (u in seen[0] && u in seen[1]) {
          console.log('>>');
          d = seen[0][u] + seen[1][u];
          console.log(finalDistance, d);

          if (!finalDistance || finalDistance > d) {
            finalDistance = d;
            console.log('final', paths);
            finalPath = paths[0][u].concat(paths[1][u].slice(0, -1).reverse());
          }
        }
      }

The logs of finalDistance and d return Infinity and NaN respectively.

Recreate the edges with a "weight" attribute of 1 and everything works.

  `var getWeight = function(e) {
    return graph.getEdgeAttribute(e, weightAttribute);
  };`

This should default to 1.

**Comment by Yomguithereal** [comment]
@brendanwheble v1.3.3 should live with the fix

**Comment by brendanwheble** [comment]
Thanks for the speedy resolution
